---
- name: Adding Repository
  apt_repository:
    repo: ppa:openjdk-r/ppa

- name: update package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: auto accept open jdk license
  command: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  changed_when: true

- name: install open jdk-java
  apt:
    name: "{{ java_version_debian }}"

- name: getting java_home path from remote host
  shell: dirname $(dirname $(readlink -f $(which java)))
  register: command_output
  changed_when: true

- name: Set Java environment in remote host
  lineinfile:
    path: /etc/environment
    line: JAVA_HOME="{{ command_output.stdout }}"

- name: reload source file
  shell: source /etc/environment
  args:
    executable: /bin/bash
  changed_when: true

  
