---
- name: Install JAVA
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ java_version_redhat }}-openjdk-devel"

- name: getting java_home path from remote host
  shell: dirname $(dirname $(readlink -f $(which java)))
  register: command_output
  changed_when: true

- name: Set Java environment in remote host
  lineinfile:
    path: /etc/environment
    line: JAVA_HOME="{{ command_output.stdout }}"

- name: reload source file
  shell: source /etc/environment
  args:
    executable: /bin/bash
  changed_when: true

