---
# tasks file for tomcat_1

#Installing java (open jdk)
#- name: Install Java 1.8
#  apt: name=openjdk-8-jdk


#Adding the group tomcat
- name: add group tomcat
  group: name="{{ group_name }}"

#Adding the user tomcat
- name: add user tomcat
  user: 
    name: "{{ user_name }}" 
    group: "{{ group_name }}" 
    home: "{{ path }}" 
    createhome: no
  become: true
  become_method: sudo

# Creating the tomcat directory
- name: create a tomcat directory
  file:
    path: "{{ path }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

#Downloading the tomcat package
- name: Download tomcat
  get_url:
     url: "{{ tomcat_download_url }}"
     dest: "{{ tomcat_download_location }}"

# Creating the tomcat directory
#- name: create a tomcat directory
#  file:
#    path: /usr/share/tomcat
#    state: directory
#    owner: tomcat
#    group: tomcat


# Extracting the tomcat archive
- name: Extract tomcat archive
  unarchive:
     src: "{{ tomcat_download_location  }}"
     dest: "{{ path }}"
     owner: "{{ user_name }}"
     group: "{{ group_name }}"
     remote_src: yes
     extra_opts: "--strip-components=1"
     creates: /usr/share/tomcat/bin

# copying the tomcat template file to the dest
- name: Copy tomcat service file
  template:
     src: templates/tomcat.service.j2
     dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

# Starting and enabling tomcat service
- name: start and enable tomcat
  service:
     daemon_reload: yes
     name: tomcat
     state: started
     enabled: yes
  become: true
  become_method: sudo
  when: ansible_service_mgr == "systemd"

- name: "show status of tomcat"
  shell: 'systemctl status tomcat'
  register: command_output

- debug:
         var: command_output.stdout_lines

